In [1]:
import numpy as np 
import pandas as pd 
import statsmodels.api as sm

In [2]:
df = sm.datasets.fair.load_pandas().data

In [3]:
df.head()

,rate_marriage,age,yrs_married,children,religious,educ,occupation,occupation_husb,affairs
0,3.0,32.0,9.0,3.0,3.0,17.0,2.0,5.0,0.111111
1,3.0,27.0,13.0,3.0,1.0,14.0,3.0,4.0,3.230769
2,4.0,22.0,2.5,0.0,1.0,16.0,3.0,5.0,1.400000
3,4.0,37.0,16.5,4.0,3.0,16.0,5.0,5.0,0.727273
4,5.0,27.0,9.0,1.0,1.0,14.0,3.0,4.0,4.666666

In [4]:
def affair_check(x):
    if x != 0:
        return 1
    else:
        return 0

df["had_affair"] = df["affairs"].apply(affair_check)

In [5]:
df.head()

,rate_marriage,age,yrs_married,children,religious,educ,occupation,occupation_husb,affairs,had_affair
0,3.0,32.0,9.0,3.0,3.0,17.0,2.0,5.0,0.111111,1
1,3.0,27.0,13.0,3.0,1.0,14.0,3.0,4.0,3.230769,1
2,4.0,22.0,2.5,0.0,1.0,16.0,3.0,5.0,1.400000,1
3,4.0,37.0,16.5,4.0,3.0,16.0,5.0,5.0,0.727273,1
4,5.0,27.0,9.0,1.0,1.0,14.0,3.0,4.0,4.666666,1

In [6]:
df["had_affair"].value_counts()

had_affair
0    4313
1    2053
Name: count, dtype: int64

In [7]:
df.groupby("had_affair").mean()

,rate_marriage,age,yrs_married,children,religious,educ,occupation,occupation_husb,affairs
had_affair,,,,,,,,,
0,4.329701,28.390679,7.989335,1.238813,2.504521,14.322977,3.405286,3.833758,0.000000
1,3.647345,30.537019,11.152460,1.728933,2.261568,13.972236,3.463712,3.884559,2.187243

In [9]:
# Create column names for the new DataFrames
occ_dummy = pd.get_dummies(df["occupation"]).astype(int)
hus_dummy = pd.get_dummies(df["occupation_husb"]).astype(int)

In [11]:
# Set X as new DataFrame without the occupation columns or the Y target
X = df.drop(columns=["occupation", "occupation_husb","affairs"], axis=1)

In [43]:
# Concat the dummy DataFrames Together
occ_dummy.columns = ["occ1", "occ2", "occ3", "occ4", "occ5", "occ6"]
hus_dummy.columns = ["hocc1", "hocc2", "hocc3", "hocc4", "hocc5", "hocc6"]
dummies = pd.concat([occ_dummy, hus_dummy], axis = 1)

In [45]:
# Now Concat the X DataFrame with the dummy variables
X = pd.concat([X, dummies], axis = 1)
X.head()

,rate_marriage,age,yrs_married,children,religious,educ,had_affair,occ2,occ3,occ4,...,occ3,occ4,occ5,occ6,hocc1,hocc2,hocc3,hocc4,hocc5,hocc6
0,3.0,32.0,9.0,3.0,3.0,17.0,1,1,0,0,...,0,0,0,0,0,0,0,0,1,0
1,3.0,27.0,13.0,3.0,1.0,14.0,1,0,1,0,...,1,0,0,0,0,0,0,1,0,0
2,4.0,22.0,2.5,0.0,1.0,16.0,1,0,1,0,...,1,0,0,0,0,0,0,0,1,0
3,4.0,37.0,16.5,4.0,3.0,16.0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
4,5.0,27.0,9.0,1.0,1.0,14.0,1,0,1,0,...,1,0,0,0,0,0,0,1,0,0

In [47]:
# Set Y as Target class, Had Affair
y = X["had_affair"]

In [49]:
# Dropping one column of each dummy variable set to avoid multicollinearity
X.drop("occ1", axis=1, inplace=True)
X.drop('hocc1', axis=1, inplace=True)
#Drop affairs column so Y target makes sense
X.drop('had_affair', axis=1, inplace=True)

In [ ]:
# This adds a column of 1's to the dataframe. 
# The model will not run without, but if 
# it could every model would try to pass through the origin

In [53]:
X.corr()

,rate_marriage,age,yrs_married,children,religious,educ,occ2,occ3,occ4,occ5,...,occ2,occ3,occ4,occ5,occ6,hocc2,hocc3,hocc4,hocc5,hocc6
rate_marriage,1.000000,-0.111127,-0.128978,-0.129161,0.078794,0.079869,-0.019697,-0.053082,0.068882,-0.002109,...,-0.019697,-0.053082,0.068882,-0.002109,0.008878,-0.038992,-0.022514,0.003303,0.003256,0.039561
age,-0.111127,1.000000,0.894082,0.673902,0.136598,0.027960,-0.034223,-0.066371,0.040982,0.079533,...,-0.034223,-0.066371,0.040982,0.079533,0.030676,-0.057368,0.011610,-0.048989,0.105525,0.083212
yrs_married,-0.128978,0.894082,1.000000,0.772806,0.132683,-0.109058,0.004668,-0.021261,-0.026816,0.076820,...,0.004668,-0.021261,-0.026816,0.076820,-0.004912,-0.033451,0.008046,-0.031121,0.092462,0.042921
children,-0.129161,0.673902,0.772806,1.000000,0.141845,-0.141918,0.081182,-0.063298,-0.003235,0.033274,...,0.081182,-0.063298,-0.003235,0.033274,-0.026830,0.001190,-0.005538,-0.008032,0.053965,0.024260
religious,0.078794,0.136598,0.132683,0.141845,1.000000,0.032245,-0.013129,-0.034986,0.043996,0.004260,...,-0.013129,-0.034986,0.043996,0.004260,0.011784,0.009990,0.008170,-0.008491,-0.000063,0.006558
educ,0.079869,0.027960,-0.109058,-0.141918,0.032245,1.000000,-0.217719,-0.335615,0.477505,-0.022121,...,-0.217719,-0.335615,0.477505,-0.022121,0.226920,-0.160756,-0.052723,-0.031422,0.042540,0.223167
occ2,-0.019697,-0.034223,0.004668,0.081182,-0.013129,-0.217719,1.000000,-0.348075,-0.251243,-0.143237,...,1.000000,-0.348075,-0.251243,-0.143237,-0.052128,0.183782,-0.020904,-0.009786,-0.093292,-0.059107
occ3,-0.053082,-0.066371,-0.021261,-0.063298,-0.034986,-0.335615,-0.348075,1.000000,-0.560645,-0.319631,...,-0.348075,1.000000,-0.560645,-0.319631,-0.116322,-0.000638,0.090043,0.011248,0.003021,-0.101673
occ4,0.068882,0.040982,-0.026816,-0.003235,0.043996,0.477505,-0.251243,-0.560645,1.000000,-0.230712,...,-0.251243,-0.560645,1.000000,-0.230712,-0.083962,-0.083123,-0.043159,0.037341,-0.001946,0.085766
occ5,-0.002109,0.079533,0.076820,0.033274,0.004260,-0.022121,-0.143237,-0.319631,-0.230712,1.000000,...,-0.143237,-0.319631,-0.230712,1.000000,-0.047868,-0.053426,-0.044053,-0.039932,0.114903,0.006016
occ6,0.008878,0.030676,-0.004912,-0.026830,0.011784,0.226920,-0.052128,-0.116322,-0.083962,-0.047868,...,-0.052128,-0.116322,-0.083962,-0.047868,1.000000,-0.046140,-0.029028,-0.043541,-0.030926,0.218824
hocc2,-0.038992,-0.057368,-0.033451,0.001190,0.009990,-0.160756,0.183782,-0.000638,-0.083123,-0.053426,...,0.183782,-0.000638,-0.083123,-0.053426,-0.046140,1.000000,-0.146849,-0.347951,-0.316693,-0.153248
hocc3,-0.022514,0.011610,0.008046,-0.005538,0.008170,-0.052723,-0.020904,0.090043,-0.043159,-0.044053,...,-0.020904,0.090043,-0.043159,-0.044053,-0.029028,-0.146849,1.000000,-0.197588,-0.179838,-0.087024
hocc4,0.003303,-0.048989,-0.031121,-0.008032,-0.008491,-0.031422,-0.009786,0.011248,0.037341,-0.039932,...,-0.009786,0.011248,0.037341,-0.039932,-0.043541,-0.347951,-0.197588,1.000000,-0.426115,-0.206198
hocc5,0.003256,0.105525,0.092462,0.053965,-0.000063,0.042540,-0.093292,0.003021,-0.001946,0.114903,...,-0.093292,0.003021,-0.001946,0.114903,-0.030926,-0.316693,-0.179838,-0.426115,1.000000,-0.187674
hocc6,0.039561,0.083212,0.042921,0.024260,0.006558,0.223167,-0.059107,-0.101673,0.085766,0.006016,...,-0.059107,-0.101673,0.085766,0.006016,0.218824,-0.153248,-0.087024,-0.206198,-0.187674,1.000000
occ2,-0.019697,-0.034223,0.004668,0.081182,-0.013129,-0.217719,1.000000,-0.348075,-0.251243,-0.143237,...,1.000000,-0.348075,-0.251243,-0.143237,-0.052128,0.183782,-0.020904,-0.009786,-0.093292,-0.059107
occ3,-0.053082,-0.066371,-0.021261,-0.063298,-0.034986,-0.335615,-0.348075,1.000000,-0.560645,-0.319631,...,-0.348075,1.000000,-0.560645,-0.319631,-0.116322,-0.000638,0.090043,0.011248,0.003021,-0.101673
occ4,0.068882,0.040982,-0.026816,-0.003235,0.043996,0.477505,-0.251243,-0.560645,1.000000,-0.230712,...,-0.251243,-0.560645,1.000000,-0.230712,-0.083962,-0.083123,-0.043159,0.037341,-0.001946,0.085766
occ5,-0.002109,0.079533,0.076820,0.033274,0.004260,-0.022121,-0.143237,-0.319631,-0.230712,1.000000,...,-0.143237,-0.319631,-0.230712,1.000000,-0.047868,-0.053426,-0.044053,-0.039932,0.114903,0.006016
occ6,0.008878,0.030676,-0.004912,-0.026830,0.011784,0.226920,-0.052128,-0.116322,-0.083962,-0.047868,...,-0.052128,-0.116322,-0.083962,-0.047868,1.000000,-0.046140,-0.029028,-0.043541,-0.030926,0.218824
hocc2,-0.038992,-0.057368,-0.033451,0.001190,0.009990,-0.160756,0.183782,-0.000638,-0.083123,-0.053426,...,0.183782,-0.000638,-0.083123,-0.053426,-0.046140,1.000000,-0.146849,-0.347951,-0.316693,-0.153248
hocc3,-0.022514,0.011610,0.008046,-0.005538,0.008170,-0.052723,-0.020904,0.090043,-0.043159,-0.044053,...,-0.020904,0.090043,-0.043159,-0.044053,-0.029028,-0.146849,1.000000,-0.197588,-0.179838,-0.087024
hocc4,0.003303,-0.048989,-0.031121,-0.008032,-0.008491,-0.031422,-0.009786,0.011248,0.037341,-0.039932,...,-0.009786,0.011248,0.037341,-0.039932,-0.043541,-0.347951,-0.197588,1.000000,-0.426115,-0.206198
hocc5,0.003256,0.105525,0.092462,0.053965,-0.000063,0.042540,-0.093292,0.003021,-0.001946,0.114903,...,-0.093292,0.003021,-0.001946,0.114903,-0.030926,-0.316693,-0.179838,-0.426115,1.000000,-0.187674
hocc6,0.039561,0.083212,0.042921,0.024260,0.006558,0.223167,-0.059107,-0.101673,0.085766,0.006016,...,-0.059107,-0.101673,0.085766,0.006016,0.218824,-0.153248,-0.087024,-0.206198,-0.187674,1.000000

In [73]:
logit = sm.Logit(y, sm.add_constant(X))

In [75]:
result = logit.fit()

Optimization terminated successfully.
         Current function value: 0.544657
         Iterations 6

LinAlgError: Singular matrix

In [77]:
result.summary()

NameError: name 'result' is not defined

In [ ]:
#result of preliminary run

In [65]:
X.drop(['children', 'educ', 'occ2', 'occ3', 'occ4', 
        'hocc2','hocc3','hocc4','hocc5','hocc6'], axis=1, inplace=True)

In [ ]:
#X.drop(columns=['children', 'educ', 'occ2', 'occ3', 'occ4', 
#        'hocc2','hocc3','hocc4','hocc5','hocc6'], inplace=True)

In [67]:
logit = sm.Logit(y, sm.add_constant(X))

In [71]:
result = logit.fit()
result.summary()

Optimization terminated successfully.
         Current function value: 0.544657
         Iterations 6

LinAlgError: Singular matrix

In [ ]:
TPR=(float(TP) / (TP + FN))
TPN=(float(TN) / (TN + FP)) 
PPV=(float(TP) / (TP + FP)) 
NPV=(float(TN) / (TN + FN)) 
FNR=(float(FN) / (FN + TP))
FPR=(float(FP) / (FP + TN))
FDR=(float(FP) / (FP + TP))
FOR=(float(FN) / (FN + TN))
TS=(float(TP) / (TP+FN + FP))
ACC=(float(TP+TN) / (TP+FP+FN + TN))  #print((TP + TN) / float(len(y_test)))

print (f"sensitivity, recall, hit rate, or true positive rate (TPR): {TPR:.3f} (# positives correctly identified)")
print (f"specificity, selectivity or true negative rate (TNR): {TPN:.3f}")
print (f"precision or positive predictive value (PPV): {PPV:.3f} (rate of correct positive predictions)")
print (f"negative predictive value (NPV): {NPV:.3f}")
print (f"miss rate or false negative rate (FNR): {FNR:.3f}")
print (f"fall-out or false positive rate (FPR): {FPR:.3f}")
print (f"false discovery rate (FDR): {FDR:.3f}")
print (f"false omission rate (FOR): {FOR:.3f}")
print("")
print (f"accuracy (ACC): {ACC:.3f} (really only useful if classes are equally represented)")